theme: jekyll-theme-slate
# remote_theme: dushyant-fire/dushyant-fire.github.io
title: Dushyant Chaudhari
description: Because coding is addictive
#logo: logo.jpeg
show_downloads: false
google_analytics:

owner:  
  name: Dushyant Chaudhari
  avatar: bio-photo.png
  twitter:  dushyant_fire
  github: dushyant-fire
  linkedin: dushyantc
# minimal_mistakes_skin: default

# Site settings
permalink: /:categories/:title/
markdown: kramdown