theme: jekyll-theme-slate
# remote_theme: dushyant-fire/dushyant-fire.github.io
title: Dushyant Chaudhari
description: Because coding is addictive
logo: logo.jpeg
show_downloads: false
google_analytics:
twitter_username: dushyant_fire
github_username: dushyant-fire
# minimal_mistakes_skin: default

# Site settings
permalink: /:categories/:title/
markdown: kramdown